### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by aminKA90** [polonez-byte-112/Altas-Notas#1]
I was trying to run your app and got the error message

File google-services.json is missing. The Google Services Plugin cannot function without it. 

I tried to find the file in your project but couldn't find.

I did a bit of a research and it says I need to get it from my project at Firebase. But since this is not my project as it is yours. Should i get it from you? Or?

Sorry, I'm still new to this. So my question may not make sense.

**Comment by polonez-byte-112** [comment]
Hi
Thanks for reporting bug. I competly forgot i hide this file. I will add it soon. Thanks for trying mine app. Curently I am fixing bugs related to mini controller so it may be unstable

**Comment by aminKA90** [comment]
If any of the bugs are not urgent to fix, perhaps you can assign to me. 

I'm trying to learn more on Android apps development, so maybe i can learn by fixing some bugs first.

**Comment by polonez-byte-112** [comment]
Thanks but I dont need help right now. This file exist but its hidden in my project for security. Its recommened to not share this file.
When I will finish fixing bugs I will send You an Apk version. Thanks for replying

**Comment by aminKA90** [comment]
Alright. Understood!

**Comment by polonez-byte-112** [comment]
Alright. I will close this for now. Thanks for reporting 😎

**Comment by polonez-byte-112** [comment]
@aminKA90  I added in README how open this repository in Your Environment
